### ISSUE TITLE
Please rewrite in rust

### ISSUE THREAD

**Issue by berserkwarwolf** [Vanilla-OS/legendary-desktop-feedback#12] opened 2024-04-01 18:39 UTC
**Is your feature request related to a problem? Please describe.**
Every software ever written in a language other than rust, should be rewritten, as suggested by development best practices.

**Describe the solution you'd like**
Rewrite LDE in rust.

**Describe alternatives you've considered**
Install POP! OS and ask ChatGPT to add AB ROOT to it.

**Additional context**
Rust adds memory safety or something like that, I can't remember.

**Comment by mirkobrombin** [comment] 2024-04-01 19:44
Duplicate of https://github.com/Vanilla-OS/legendary-desktop-feedback/issues/11

**Closed as completed by mirkobrombin** 2024-04-01 19:44 UTC
